### PR TITLE
Dashboard

### PR DESCRIPTION
**Pull request by moguetn**
Dashboard page added. See commit notes for details

### CODE REVIEW

**Comment by joyceawt** [comment]
1. need to merge main into your branch as there's conflicts.
2. I don't think this is the best UX here. Screenshot 2024-05-23 at 11 09 17 AM
3. Dashboard should be added to the nav bar when user is logged in. would be better for UX
4. The side nav CSS should be aligned with the resume page. its a bit off right now the paddings aren't right
Screenshot 2024-05-23 at 11 10 34 AM
5. Based on the screenshot above again - i think the skills shouldn't be liad out like that it's super hard to read. doing it per line like this is probably not the best ux. there's also more CSS to be fixed between edit role and no role defined. 
6. Should user profile be the first thing a user sees when navigating to dashboard? seems a bit weird because I'd expect user profile to be more like settings. 
7. CSS on settings page and paddings are really off as well. also the color (buttons etc) should be changed to match the overall website's color scheme
Screenshot 2024-05-23 at 11 12 46 AM

**Comment by joyceawt** [comment]
EDIT: just realized the landing page checkbox is already on main. i think maybe remove all the skills joined. just check to search with skills, it is way too long/doesn't look good right now

**Review by joyceawt — CHANGES_REQUESTED** [review]
didn't trigger comments so doing it here but just realized i didn't leave the comments for the code:

1. FetchUsers - was this an addition an accident? This is a security risk it shouldn't be available.
2. Theres an "old" and "new" dashboard. i think you should remove the one you don't need to avoid committing unneeded files
3. I see things like saved jobs and stuff in the code but i wasn't able to see this when i checked into the branch and tested?

**Comment by moguetn** [comment]
1. Merged conflicts
2. Agreed. Quick fix so just removed list of skills
3. Agreed - not a quick fix, so can be slated as a future fix
4. Agreed - not a quick fix, so can be slated as a future fix
5. Agreed - not a quick fix, so can be slated as a future fix
6. Yeah, I agree this isn’t an ideal layout and was just hastily adjusted to look like this last-minute once it was clear that we wouldn’t have time to build out more a proper, user-centric dashboard with saved jobs, application tracking, recommended jobs, etc.
7. Agreed - not a quick fix, so can be slated as a future fix

Second set:
1. Yeah, I don’t even remember why this was created, but it’s now removed
2. Old dashboard removed for cleanliness
3. Removed references to saved jobs for cleanliness

**Review by joyceawt — APPROVED** [review]
approving this PR to merge after fixing what i can with visible UX. 
lots of areas of improvement for code quality but since its functional and looks better now im just going to merge it

**Pull request merged**
